### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by stephengold** [capdevon/Archer-Game-Template#1]
I'm seeing the following build errors when I build on Linux using Gradle 4.4.1:

```console
sgold:~/Git/ext/Archer-Game-Template$ gradle run

> Task :compileJava 
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/mygame/PlayerControl.java:27: error: class PlayerManager is public, should be declared in a file named PlayerManager.java
public class PlayerManager extends SimpleAppState {
       ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/mygame/PlayerInput.java:15: error: cannot find symbol
    private PlayerControl playerControl;
            ^
  symbol:   class PlayerControl
  location: class PlayerInput
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/mygame/PlayerManager.java:30: error: cannot find symbol
    private PlayerControl playerCtrl;
            ^
  symbol:   class PlayerControl
  location: class PlayerManager
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:17: error: package com.jme3.post.filters does not exist
import com.jme3.post.filters.BloomFilter;
                            ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:18: error: package com.jme3.post.filters does not exist
import com.jme3.post.filters.LightScatteringFilter;
                            ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/control/Animator.java:81: error: cannot find symbol
    public Node getAttachments(String boneName) {
           ^
  symbol:   class Node
  location: class Animator
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/Shadow.java:13: warning: [deprecation] BasicShadowRenderer in com.jme3.shadow has been deprecated
import com.jme3.shadow.BasicShadowRenderer;
                      ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/WaterFactory.java:10: error: package com.jme3.water does not exist
import com.jme3.water.SimpleWaterProcessor;
                     ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/mygame/PlayerInput.java:21: error: cannot find symbol
            this.playerControl = getComponent(PlayerControl.class);
                                              ^
  symbol:   class PlayerControl
  location: class PlayerInput
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/mygame/PlayerManager.java:46: error: cannot find symbol
        player = (Node) assetManager.loadModel(IAnimation.MODEL);
                                               ^
  symbol:   variable IAnimation
  location: class PlayerManager
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/mygame/PlayerManager.java:57: error: cannot find symbol
        playerCtrl = new PlayerControl();
                         ^
  symbol:   class PlayerControl
  location: class PlayerManager
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/mygame/PlayerManager.java:88: error: cannot find symbol
        Node rh = AnimUtils.getAttachments(player, IAnimation.RIGHT_HAND);
                                                   ^
  symbol:   variable IAnimation
  location: class PlayerManager
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:65: error: cannot find symbol
        LightScatteringFilter lsf = new LightScatteringFilter(lightDir.mult(-300));
        ^
  symbol:   class LightScatteringFilter
  location: class BaseGameApplication
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:65: error: cannot find symbol
        LightScatteringFilter lsf = new LightScatteringFilter(lightDir.mult(-300));
                                        ^
  symbol:   class LightScatteringFilter
  location: class BaseGameApplication
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:68: error: cannot find symbol
        BloomFilter bloom = new BloomFilter();
        ^
  symbol:   class BloomFilter
  location: class BaseGameApplication
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:68: error: cannot find symbol
        BloomFilter bloom = new BloomFilter();
                                ^
  symbol:   class BloomFilter
  location: class BaseGameApplication
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/Shadow.java:52: warning: [deprecation] BasicShadowRenderer in com.jme3.shadow has been deprecated
        BasicShadowRenderer shadowRenderer = new BasicShadowRenderer(assetManager, 2048);
        ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/Shadow.java:52: warning: [deprecation] BasicShadowRenderer in com.jme3.shadow has been deprecated
        BasicShadowRenderer shadowRenderer = new BasicShadowRenderer(assetManager, 2048);
                                                 ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/WaterFactory.java:23: error: cannot find symbol
                SimpleWaterProcessor wpss = new SimpleWaterProcessor(assetManager);
                ^
  symbol:   class SimpleWaterProcessor
  location: class WaterFactory
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/WaterFactory.java:23: error: cannot find symbol
                SimpleWaterProcessor wpss = new SimpleWaterProcessor(assetManager);
                                                ^
  symbol:   class SimpleWaterProcessor
  location: class WaterFactory
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/engine/AsyncOperation.java:58: warning: [unchecked] unchecked method invocation: method thenAccept in class CompletableFuture is applied to given types
        future.thenAccept(action);
                         ^
  required: Consumer<? super T>
  found: Consumer
  where T is a type-variable:
    T extends Object declared in class CompletableFuture
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/engine/AsyncOperation.java:58: warning: [unchecked] unchecked conversion
        future.thenAccept(action);
                          ^
  required: Consumer<? super T>
  found:    Consumer
  where T is a type-variable:
    T extends Object declared in class CompletableFuture
17 errors
5 warnings


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
1 actionable task: 1 executed
sgold:~/Git/ext/Archer-Game-Template$ gradle -v

------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.17
Ant:          Apache Ant(TM) version 1.10.7 compiled on October 24 2019
JVM:          1.8.0_272 (Private Build 25.272-b10)
OS:           Linux 5.4.0-52-generic amd64

sgold:~/Git/ext/Archer-Game-Template$
```

**Comment by capdevon** [comment]
Hi Stephen, thanks for reporting. I believe I have eliminated all errors. I've done some feature upgrades. Let me know if there are still compiling problems.

**Comment by stephengold** [comment]
Thanks for your quick response to my issue.

I did a "git pull" (from https://github.com/capdevon/Archer-Game-Template 2d1ae15..c378b49  main -> origin/main) then attempted a clean build, but I am still seeing compilation errors:
```text
sgold:~/Git/ext/Archer-Game-Template$ gradle clean build
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :compileJava 
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/control/Animator.java:81: error: cannot find symbol
    public Node getAttachments(String boneName) {
           ^
  symbol:   class Node
  location: class Animator
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:17: error: package com.jme3.post.filters does not exist
import com.jme3.post.filters.BloomFilter;
                            ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:18: error: package com.jme3.post.filters does not exist
import com.jme3.post.filters.LightScatteringFilter;
                            ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/Shadow.java:13: warning: [deprecation] BasicShadowRenderer in com.jme3.shadow has been deprecated
import com.jme3.shadow.BasicShadowRenderer;
                      ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/WaterFactory.java:10: error: package com.jme3.water does not exist
import com.jme3.water.SimpleWaterProcessor;
                     ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:65: error: cannot find symbol
        LightScatteringFilter lsf = new LightScatteringFilter(lightDir.mult(-300));
        ^
  symbol:   class LightScatteringFilter
  location: class BaseGameApplication
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:65: error: cannot find symbol
        LightScatteringFilter lsf = new LightScatteringFilter(lightDir.mult(-300));
                                        ^
  symbol:   class LightScatteringFilter
  location: class BaseGameApplication
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:68: error: cannot find symbol
        BloomFilter bloom = new BloomFilter();
        ^
  symbol:   class BloomFilter
  location: class BaseGameApplication
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/BaseGameApplication.java:68: error: cannot find symbol
        BloomFilter bloom = new BloomFilter();
                                ^
  symbol:   class BloomFilter
  location: class BaseGameApplication
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/Shadow.java:52: warning: [deprecation] BasicShadowRenderer in com.jme3.shadow has been deprecated
        BasicShadowRenderer shadowRenderer = new BasicShadowRenderer(assetManager, 2048);
        ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/Shadow.java:52: warning: [deprecation] BasicShadowRenderer in com.jme3.shadow has been deprecated
        BasicShadowRenderer shadowRenderer = new BasicShadowRenderer(assetManager, 2048);
                                                 ^
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/WaterFactory.java:23: error: cannot find symbol
                SimpleWaterProcessor wpss = new SimpleWaterProcessor(assetManager);
                ^
  symbol:   class SimpleWaterProcessor
  location: class WaterFactory
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/util/WaterFactory.java:23: error: cannot find symbol
                SimpleWaterProcessor wpss = new SimpleWaterProcessor(assetManager);
                                                ^
  symbol:   class SimpleWaterProcessor
  location: class WaterFactory
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/engine/AsyncOperation.java:58: warning: [unchecked] unchecked method invocation: method thenAccept in class CompletableFuture is applied to given types
        future.thenAccept(action);
                         ^
  required: Consumer<? super T>
  found: Consumer
  where T is a type-variable:
    T extends Object declared in class CompletableFuture
/home/sgold/Git/ext/Archer-Game-Template/src/main/java/com/capdevon/engine/AsyncOperation.java:58: warning: [unchecked] unchecked conversion
        future.thenAccept(action);
                          ^
  required: Consumer<? super T>
  found:    Consumer
  where T is a type-variable:
    T extends Object declared in class CompletableFuture
10 errors
5 warnings


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
6 actionable tasks: 2 executed, 4 up-to-date
sgold:~/Git/ext/Archer-Game-Template$

```

**Comment by capdevon** [comment]
ok I think I solved all the errors. 
I corrected the errors of the Animator class.
I updated the **build.gradle** file by adding the module for post processing filters: **implementation 'org.jmonkeyengine:jme3-effects:' + jmonkeyengineVersion**

Let me know if there are still compiling problems.

**Comment by stephengold** [comment]
No more compile-time errors. There is a runtime error, but I will open an new issue for that.
